export const appConstants = {
  FETCH_APPS_REQUEST: "FETCH_LEADS_REQUEST",
  FETCH_ADMIN_APPS: "FETCH_ADMIN_LEADS",
  FETCH_SINGLE_APP: "FETCH_SINGLE_APP",
  FETCH_FAILURE: "FETCH_FAILURE",
  ADD_APP: "ADD_APP",
  ADD_APP_FAILURE: "ADD_APP",
  DELETE_APP: "DELETE_APP",
  DELETE_APP_FAILURE: "DELETE_APP_FAILURE",
};
