export const linkConstants = {
  FETCH_LINKS_REQUEST: "FETCH_LINKS_REQUEST",
  ADD_LINK_LEVELS: "ADD_LINK_LEVELS",
  ADD_FAILURE: "ADD_FAILURE",
  SEARCH_LINK_LEVELS: "SEARCH_LINK_LEVELS",
  FETCH_LINK_LEVELS: "FETCH_LINK_LEVELS",
  FETCH_FAILURE: "FETCH_FAILURE",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};
