export const webinarConstants = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_FAILURE: "FETCH_FAILURE",
  FETCH_WEBINAR: "FETCH_WEBINAR",
  FETCH_ALL_WEBINARS: "FETCH_ALL_WEBINARS",
  SET_WEBINAR_ID: "SET_WEBINAR_ID",
  FETCH_FORM_DATA: "FETCH_FORM_DATA",
};
